Modifying the code to show the most updated latency
dmihal/ethereum-nodes pull request #8
Opened 2022-07-28 09:16 UTC by HopLilBunnyHop

Hey man really love your work here. It is really useful for my company and clients. 
However, there is one thing that bugs me - the number seems to be unchanged from time to time, which is unlikely in the real world. After diving into the source code I realized that you are using Static prop instead of server-side prop. Is this intentional?
Anyway, I just applied a quick fix here, hope it helps.

I modified the nodes.ts too because the real-time latency seems to be very unstable.  Therefore I modify the code to show an average latency of 5 requests instead of one. Which makes things a little bit better.
Anyway, Cheers mate.
Your work is cool, hope to see more from you.

2022-08-24 02:37 UTC, hoplilbunnyhophophop commented
Hi David
I manage to get some nodes up and running. 
Chainstack works like a charm. 
Quicknode was tested with a non-pro account so the link was different. It works after modifying the original URL.
Archivednode didn't reply to my request so I couldn't get an endpoint from them. 😔
Maybe there is some mistake in the environment variable setting. Do you mind taking a look at that?
I would love to help with testing if you can trust me with your credentials. 🤔
Cheers

2022-09-26 19:58 UTC, TABASCOatw commented
bump @dmihal

2022-10-17 18:59 UTC, dmihal requested changes
Hey, overall this makes sense (averaging 5 queries), however the page should stay as `getStaticProps`

2022-10-17 18:59 UTC, dmihal commented on pages/index.tsx
> +export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
Hey, we use Static props so that the page is background-refreshed, therefore the user doesn't need to wait for the page to load

2022-10-18 19:51 UTC, hoplilbunnyhophophop approved these changes
Makes sense!

2022-10-31 03:25 UTC, HopLilBunnyHop commented
I am gonna close this one and open a new PR.

2022-10-31 03:25 UTC, closed without merging